### ISSUE TITLE
Discuss style guides

### ISSUE THREAD

**Issue by cceckman** [aaronbloomfield/pdr#68]
Style guides are important to good software engineering at scale. They help programmers to produce shareable and less-buggy code, and they encourage programmers to think about language design and capabilities.

As far as I recall, style guides aren't covered in the UVA curriculum. They are a more software-engineering-oriented topic than many things in this course; however, I think they would fit in well in explaining some of the patterns (INCLUDE guards, file breakup, references v. const references v. pointers). Also (in my limited experience) there's more variety in C/C++ style guides than in Java, so covering them in 2150 could help.

Some examples:
http://google-styleguide.googlecode.com/svn/trunk/cppguide.html
   (I like the "don't use non-const references" rule.)
http://lars-lab.jpl.nasa.gov/JPL_Coding_Standard_C.pdf

**Comment by mrecachinas** [comment]
I agree with @cceckman. It is worth considering because I've heard there might have been students in the past who don't know what tabs are (or even as extreme as writing everything on one line).

It's worth enforcing some semblance of style -- i.e., "if your code is unreadable, -5" or something. I know Sherriff and Horton used a similar rule (for unformatted code) in 1110 and 2110.

**Comment by aaronbloomfield** [comment]
Moved to https://github.com/markfloryan/pdr/issues/19
